# serverless.yml

service: express-app

provider:
  name: aws
  runtime:  nodejs12.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true